---
- name: Deploy VM in RHEV
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    vm_name: mustafa_ansible_test1
  tasks:
    - name: Log in to RHEV/oVirt
      ovirt.ovirt.ovirt_auth:
        url: "https://rhvm.wikilabs.local/ovirt-engine/api"
        username: "ansibletest@internal"
        password: "Wiki@2051"


    - name: get info
      ansible.builtin.debug:
        msg: "{{ ovirt_auth }}"


  collections:
    - ovirt.ovirt
